name: CI Pipeline
on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: |
        dotnet restore HabitTracker/HabitTracker.sln --no-cache
        dotnet restore HabitTracker/HabitTracker.csproj -r win10-x64
        dotnet restore HabitTracker/HabitTracker.csproj -r android-arm
        dotnet restore HabitTracker/HabitTracker.csproj -r android-arm64
        dotnet restore HabitTracker/HabitTracker.csproj -r android-x64
        dotnet restore HabitTracker/HabitTracker.csproj -r android-x86
    - name: Build solution
      run: dotnet build HabitTracker/HabitTracker.sln --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test HabitTracker.Test/HabitsTracker.Test.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        files: ./HabitsTracker.Test/TestResults/*/coverage.cobertura.xml
        fail_ci_if_error: true
