name: CI Pipeline
on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: |
        dotnet restore HabitTracker/HabitTracker.sln --no-cache
        dotnet restore HabitTracker/HabitTracker.csproj -r win-x64
        dotnet restore HabitTracker/HabitTracker.csproj -r android-arm64
    - name: Build solution
      run: dotnet build HabitTracker/HabitTracker.sln --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test HabitTracker.Test/HabitTracker.Test.csproj --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
